spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8
    username: root
    password: 123
    tomcat:
      max-active: 20 #最大活跃数
      initial-size: 1 #初始化数量
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

    dbcp2:
      pool-prepared-statements: true
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: mysql
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


